#! /usr/bin/env bash

# Print an error message and exit.
panic()
{
	echo "ERROR: $@"
	exit 1
}

# Get the directory in which the currently running script is located.
cmd_dir=$(dirname "$0") || panic "cannot determine command directory"
# downloading picture of italy from space sentinel 2 satellite
wget "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2015/06/northwest_italy_and_southern_france/15492215-1-eng-GB/Northwest_Italy_and_southern_France_pillars.jpg" -O "$cmd_dir/italy.jpg"
quantize_image="$cmd_dir/quantize_image $cmd_dir/italy.jpg 5"

#ls "$cmd_dir"
#ls "$cmd_dir/../"
#ls "$cmd_dir/../../"
#ls "$cmd_dir/../../../"
#ls "$cmd_dir/../../../validate"
#echo -e "\n"
#ls "$cmd_dir/../../../../"

echo "Running image quantization example..."
$quantize_image || panic "Image quantization failed"
